import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { serverSideTranslation } from "@/lib/i18n/server";
import I18NProvider from "@/components/i18n/translations-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
}) {
  const namespaces = ["home"];
  const { resources } = await serverSideTranslation(locale, namespaces);

  return (
    <I18NProvider locale={locale} namespaces={namespaces} resources={resources}>
      <html lang={locale}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        </body>
      </html>
    </I18NProvider>
  );
}
